### ISSUE TITLE
TODO: Translate into various languages (on-hold)

### ISSUE THREAD

**Issue by vypr** [retejo/legacy#12]
As black and white as it can get, I need someone to translate either the i18n/esperanto.json or  i18n/english.json files into one of these languages, as I don't know them personally, but we can greatly benefit from having them around.

Please use formal words in your translations, also. Multajn dankojn! (Many thanks!)

This is on-hold for the moment. While we have some translations, we will need more done as we get more done, so please do not contribute any translations until we are finished. If you submit a grammatical improvement to a translation, they will be approved as well.

The currently existing translations that were submitted before this edit will still exist, they will need to be edited with more phrases translated eventually.

To list what we need by priority:

- [ ] Spanish
- [ ] French
- [ ] German
- [ ] Italian
- [ ] Portuguese
- [ ] Russian
- [ ] Ukrainian
- [ ] Polish
- [ ] Mandarin Chinese
- [ ] Greek

If there's a language not listed but you would still like to contribute, go for it! I'm not gonna stop you from helping out. :)

**Comment by hi15** [comment]
I will translate to portuguese!

**Comment by vypr** [comment]
@hi15 Fantastic! I'll happily await your PR. :heart:

**Comment by jnethe** [comment]
think I can knock out the Spanish - looking to do first PRs (convinced by a t-shirt to try my hand at software) - git is hard - the Spanish is easy

**Comment by vypr** [comment]
@jnethe Someone beat you to it :)

**Comment by MinerBigWhale** [comment]
I will translate it to French

**Comment by vypr** [comment]
@MinerBigWhale Thank you plenty :)

**Comment by vypr** [comment]
Accidentally closed the issue, don't mind it.

**Comment by jnethe** [comment]
thanks a ton for accepting my slight edits - I learned a ton tonight on github with your project - Happy Halloween

**Comment by djbb7** [comment]
Added the translation to Italian. Happy Halloween :)

**Comment by modkaffes** [comment]
@vypr, here's the greek translation! #32

**Comment by vypr** [comment]
Thank you to @hi15, @jnethe, @MinerBigWhale, @anmrdz, @djbb7, and @modkaffes for all your work! I'm very thankful for you guys helping out our little project, I didn't think anyone would help out, with GitHub being such a large place.

Thanks again, guys. :heart:
